### ISSUE TITLE
Documentation of available extensions

### ISSUE THREAD

**Issue by pboling** [aptible/docker-postgresql#71]
[Documentation site](https://www.aptible.com/documentation/enclave/reference/databases/supported/postgresql.html#extensions) says I can find a list of extensions here in this repo.  I was hoping to learn what the `minimal number of extensions installed` with the default image are, but I can't find it.

> Enclave supports two families of images for Postgres: default and contrib.
> The default images have a minimal number of extensions installed, but do include PostGIS.
> The alternative contrib images have a larger number of useful extensions installed. The list of available extensions is visible in the repository we use to manage those images: aptible/docker-postgresql.

Is this documented anywhere?  I need to know if I can use `uuid-ossp` on the default image.  I can't find the string anywhere in the entire repo, but it has been an extension since at least PG 8 and is a fairly common use case now (generating / storing `UUID` data).

**Comment by krallin** [comment]
The default images use the extensions that Postgres itself ships with — that includes `uuid-ossp` . That said, if you'd like to know _exactly_ what is available, you can run: `SELECT * FROM pg_available_extensions;` through e.g. a DB tunnel and get the full list.
