### ISSUE TITLE
wal2json not installed

### ISSUE THREAD

**Issue by joshraker** [aptible/docker-postgresql#72]
Despite our tests for wal2json, it is not being installed on our image. `find / -name *wal2json*` produces no results whereas, when I manually installed it in a container, there was a `/usr/lib/postgresql/10/lib/wal2json.so` library. When I manually run the test `SELECT 'init' FROM pg_create_logical_replication_slot('test_slot', 'wal2json');`, I get the following error and an exit status of 1: `ERROR:  could not access file "wal2json": No such file or directory`.

Zendesk Ticket: https://aptible.zendesk.com/agent/tickets/19593

**Comment by almathew** [comment]
This was resolved - the wal2json plugin was/is only available in the -contrib flavor of the PostgreSQL images, which is intended.

**Comment by hjhart** [comment]
Came across this but didn't fully understand what to do. You can run this command to create a postgres image with a contrib variety.

```
aptible db:create postgres-wal2json-test --type postgresql --version 12-contrib --environment YOUR_ENVIRONMENT_HERE
```

You can see all versions of databases available by running

```
aptible db:versions
```

Which is as of today returning
```
=== postgresql
9.5-contrib-frozen
9.5-frozen
13-contrib
13
12-contrib
12
11-contrib
11
10-contrib
10
9.6-contrib
9.6
9.5-contrib
9.3
9.4
9.5
```
